export const IS_LOADING_FALSE = "AUTH/IS_LOADING_FALSE";
export const IS_LOADING_TRUE = "AUTH/IS_LOADING_TRUE";
export const SHOW_ALERT = "AUTH/SHOW_ALERT";
export const HIDE_ALERT = "AUTH/HIDE_ALERT";
export const IS_AUTH_USER = "AUTH/IS_AUTH_USER";
export const AUTH_TOKEN = "AUTH/AUTH_TOKEN"
export const MENU_GET_ALL = "MENU/MENU_GET_ALL"
