export const POST_REGISTER = 'AUTH/POST_REGISTER'
export const POST_LOGIN = 'AUTH/POST_LOGIN'
export const IS_LOADING_FALSE = 'AUTH/IS_LOADING_FALSE'
export const IS_LOADING_TRUE = 'AUTH/IS_LOADING_TRUE'